apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine-pod
  name: alpine-pod
spec:
  containers:
  - image: alpine:3.14
    name: alpine-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
