apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jenkins
  name: jenkins
spec:
  containers:
  - image: jenkins/jenkins
    name: jenkins
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
