apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: node
  name: node
spec:
  containers:
  - image: node
    name: node
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
